# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: vakande <vakande@student.42barcelona.      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/01/15 18:51:47 by vakande           #+#    #+#              #
#    Updated: 2025/01/15 18:56:13 by vakande          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_diaplay_file
FILES = display_file.c

.PHONY: all clean fclean

all:
		@gcc -Wall -Wextra -Werror -o $(NAME) $(FILES)

clean:
		@rm -f *.o

fclean: clean
		@rm -f $(NAME)
